### ISSUE TITLE
이미지 변경 이슈

### ISSUE THREAD

**Issue by eastroots92** [JeaSungLEE/resume#6]
제가 PR 날렸던 이미지가 giphy에서 직접 호출해서 쓰다보니 이미지가 깨지는 이슈가 있는 듯 합니다. 🧐

https://user-images.githubusercontent.com/26288794/73801958-6c741180-47ff-11ea-805d-108c9266c8e8.gif

요 URL로 바꿔주실 수 있나요?

![giphy](https://user-images.githubusercontent.com/26288794/73801958-6c741180-47ff-11ea-805d-108c9266c8e8.gif)

**Comment by JeaSungLEE** [comment]
넵 변경하였습니다.
